//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminRoleAction
    {
        public int AdmRoleAction_Id { get; set; }
        public System.Guid AdmAction_Id { get; set; }
        public System.Guid AdmRole_Id { get; set; }
    
        public virtual AdminAction AdminAction { get; set; }
        public virtual AdminRole AdminRole { get; set; }
    }
}
