//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdminAction()
        {
            this.AdminRoleActions = new HashSet<AdminRoleAction>();
        }
    
        public System.Guid AdmAction_Id { get; set; }
        public string AdmAction_Controller { get; set; }
        public string AdmAction_Action { get; set; }
        public string AdmAction_Title { get; set; }
        public bool AdmAction_IsMenu { get; set; }
        public int AdmAction_MenuIndex { get; set; }
        public string AdmAction_MenuIcon { get; set; }
        public bool AdmAction_AccessForAll { get; set; }
        public string AdmAction_Parrent { get; set; }
        public string AdmActionMenuClass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminRoleAction> AdminRoleActions { get; set; }
    }
}
