//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUserHistory
    {
        public long AUH_Id { get; set; }
        public System.DateTime AUH_CreateDate { get; set; }
        public long AdmUsr_Id { get; set; }
        public string AUH_IP { get; set; }
        public string AUH_Device { get; set; }
        public string AUH_IPInfo { get; set; }
        public string AUH_Action { get; set; }
        public string AUH_QuerString { get; set; }
        public string AUH_Tag { get; set; }
    
        public virtual AdminUser AdminUser { get; set; }
    }
}
