//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BotCardsWithraw
    {
        public long Bcw_Id { get; set; }
        public string BankName { get; set; }
        public string CardNumber { get; set; }
        public int CVV2 { get; set; }
        public double Limit { get; set; }
        public string Index { get; set; }
        public System.Guid BankKey { get; set; }
        public bool Enabled { get; set; }
        public int Order { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string Shaba { get; set; }
    }
}
