//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BotInfoWithraw
    {
        public long Biw_Id { get; set; }
        public string BotName { get; set; }
        public System.Guid Key { get; set; }
        public System.DateTime LastSeen { get; set; }
        public int BotType { get; set; }
        public int Order { get; set; }
        public bool Active { get; set; }
    }
}
