//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardToCardRequest
    {
        public System.Guid CR_Id { get; set; }
        public long CR_Amount { get; set; }
        public int CR_Status { get; set; }
        public Nullable<System.DateTime> CR_CreateDate { get; set; }
        public long Usr_Id { get; set; }
        public Nullable<System.Guid> Drq_Id { get; set; }
        public Nullable<System.Guid> Dpw_Id { get; set; }
        public int Aff_Id { get; set; }
    
        public virtual Affiliate Affiliate { get; set; }
        public virtual DealRequest DealRequest { get; set; }
        public virtual DepositeWallet DepositeWallet { get; set; }
        public virtual User User { get; set; }
    }
}
