//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardToCardTransaction
    {
        public int CT_Id { get; set; }
        public long CT_DebitAmount { get; set; }
        public long CT_CreditAmount { get; set; }
        public string CT_Description { get; set; }
        public long CT_Balance { get; set; }
        public string CT_TransactionTrace { get; set; }
        public string CT_StatementStatus { get; set; }
        public string CT_DestinationAccount { get; set; }
        public string CT_AdditionalInfo1 { get; set; }
        public string CT_AdditionalInfo2 { get; set; }
        public System.DateTime CT_CreateDate { get; set; }
    }
}
