//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataContext : DbContext
    {
        public DataContext()
            : base("name=DataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DepositeWallet> DepositeWallets { get; set; }
        public virtual DbSet<MenuNotification> MenuNotifications { get; set; }
        public virtual DbSet<RefralCommision> RefralCommisions { get; set; }
        public virtual DbSet<WebhockHistoryTokenView> WebhockHistoryTokenViews { get; set; }
        public virtual DbSet<AdminAction> AdminActions { get; set; }
        public virtual DbSet<AdminRoleAction> AdminRoleActions { get; set; }
        public virtual DbSet<AdminRole> AdminRoles { get; set; }
        public virtual DbSet<AdminUserHistory> AdminUserHistories { get; set; }
        public virtual DbSet<Affiliate> Affiliates { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<CurrencyPriceHistory> CurrencyPriceHistories { get; set; }
        public virtual DbSet<DealRequest> DealRequests { get; set; }
        public virtual DbSet<Domain> Domains { get; set; }
        public virtual DbSet<DoucumentUserWithdraw> DoucumentUserWithdraws { get; set; }
        public virtual DbSet<HelpPage> HelpPages { get; set; }
        public virtual DbSet<MarketingChannelClick> MarketingChannelClicks { get; set; }
        public virtual DbSet<MarketingChannel> MarketingChannels { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TicketItem> TicketItems { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<TicketSubject> TicketSubjects { get; set; }
        public virtual DbSet<TicketTemplate> TicketTemplates { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<UserBankCard> UserBankCards { get; set; }
        public virtual DbSet<UserHistory> UserHistories { get; set; }
        public virtual DbSet<UserRelatedAccount> UserRelatedAccounts { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserVerificationDoc> UserVerificationDocs { get; set; }
        public virtual DbSet<UserWithdraw> UserWithdraws { get; set; }
        public virtual DbSet<Wallet> Wallets { get; set; }
        public virtual DbSet<WebhockHisory> WebhockHisories { get; set; }
        public virtual DbSet<BotCardsWithraw> BotCardsWithraws { get; set; }
        public virtual DbSet<BotInfoWithraw> BotInfoWithraws { get; set; }
        public virtual DbSet<BotWithrawType> BotWithrawTypes { get; set; }
        public virtual DbSet<LifeLogBotWithraw> LifeLogBotWithraws { get; set; }
        public virtual DbSet<OptBotWithraw> OptBotWithraws { get; set; }
        public virtual DbSet<ReservationWallet> ReservationWallets { get; set; }
        public virtual DbSet<TransactionId> TransactionIds { get; set; }
        public virtual DbSet<WithdrawCrypto> WithdrawCryptoes { get; set; }
        public virtual DbSet<SMSSender> SMSSenders { get; set; }
        public virtual DbSet<LogUserWallet> LogUserWallets { get; set; }
        public virtual DbSet<UserWalletReservation> UserWalletReservations { get; set; }
        public virtual DbSet<AdminSMSVerification> AdminSMSVerifications { get; set; }
        public virtual DbSet<Gateway> Gateways { get; set; }
        public virtual DbSet<AdminUser> AdminUsers { get; set; }
    }
}
