//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DealRequest()
        {
            this.WithdrawCryptoes = new HashSet<WithdrawCrypto>();
            this.Gateways = new HashSet<Gateway>();
        }
    
        public System.Guid Drq_Id { get; set; }
        public System.DateTime Drq_CreateDate { get; set; }
        public int Aff_Id { get; set; }
        public int Cur_Id { get; set; }
        public double Drq_Amount { get; set; }
        public double Drq_Cur_Latest_Price { get; set; }
        public long CPH_Id { get; set; }
        public double Drq_TotalPrice { get; set; }
        public Nullable<long> Usr_Id { get; set; }
        public int Drq_Type { get; set; }
        public int Drq_Status { get; set; }
        public string Drq_RefrenceID { get; set; }
        public string Drq_Tag1 { get; set; }
        public string Drq_Tag2 { get; set; }
        public Nullable<int> Drq_VerificationType { get; set; }
        public int Drq_VerificationStatus { get; set; }
        public Nullable<long> AdmUsr_Id { get; set; }
        public string AdmUsr_Description { get; set; }
        public Nullable<int> Wal_Id { get; set; }
        public string Drq_UsrWalletAddress { get; set; }
        public string Txid { get; set; }
    
        public virtual Affiliate Affiliate { get; set; }
        public virtual CurrencyPriceHistory CurrencyPriceHistory { get; set; }
        public virtual User User { get; set; }
        public virtual Wallet Wallet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WithdrawCrypto> WithdrawCryptoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gateway> Gateways { get; set; }
        public virtual AdminUser AdminUser { get; set; }
    }
}
