//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domain
    {
        public int Dmn_Id { get; set; }
        public int Aff_Id { get; set; }
        public string Dmn_Domain { get; set; }
        public string Dmn_NS1 { get; set; }
        public string Dmn_NS2 { get; set; }
        public bool Dmn_IsActive { get; set; }
        public bool Dmn_FilterStatus { get; set; }
        public string Dmn_Description { get; set; }
        public string Dmn_CloudflareID { get; set; }
    
        public virtual Affiliate Affiliate { get; set; }
    }
}
