//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoucumentUserWithdraw
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoucumentUserWithdraw()
        {
            this.UserWithdraws = new HashSet<UserWithdraw>();
        }
    
        public long Doc_Id { get; set; }
        public string Doc_Image { get; set; }
        public string Doc_Title { get; set; }
        public string Doc_Message { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserWithdraw> UserWithdraws { get; set; }
    }
}
