//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gateway
    {
        public int GW_Id { get; set; }
        public string GW_RefId { get; set; }
        public double GW_Price { get; set; }
        public System.DateTime GW_CreateDate { get; set; }
        public int GW_Status { get; set; }
        public Nullable<System.Guid> Drq_Id { get; set; }
        public Nullable<System.Guid> Dpw_Id { get; set; }
    
        public virtual DepositeWallet DepositeWallet { get; set; }
        public virtual DealRequest DealRequest { get; set; }
    }
}
