//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelpPage
    {
        public long Page_Id { get; set; }
        public string Page_Subject { get; set; }
        public string Page_Content { get; set; }
        public int Page_Status { get; set; }
        public System.DateTime Page_CreatedDate { get; set; }
        public int Page_OrderIndex { get; set; }
        public long AdmUsr_Id { get; set; }
        public Nullable<System.Guid> Page_FileID { get; set; }
    
        public virtual AdminUser AdminUser { get; set; }
    }
}
