//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketingChannelClick
    {
        public long MCC_Id { get; set; }
        public System.DateTime MCC_CreateDate { get; set; }
        public string MCC_IP { get; set; }
        public string MCC_BrowserUserAgent { get; set; }
        public int Mch_Id { get; set; }
    
        public virtual MarketingChannel MarketingChannel { get; set; }
    }
}
