//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuNotification
    {
        public int Men_Id { get; set; }
        public int Men_DealRequest { get; set; }
        public int Men_User { get; set; }
        public int Men_Transaction { get; set; }
        public int Men_Ticket { get; set; }
        public int Men_Withraw { get; set; }
        public int Men_VerificationDocument { get; set; }
        public int Men_BankCard { get; set; }
        public int Men_WebhockTokenView { get; set; }
        public int Men_DepositWallet { get; set; }
    }
}
