//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptBotWithraw
    {
        public long Obw_Id { get; set; }
        public string MaskCardNumber { get; set; }
        public string OPT { get; set; }
        public double Amount { get; set; }
        public string Time { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
