//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefralCommision
    {
        public int RefCom_Id { get; set; }
        public double RefCom_Amount { get; set; }
        public double RefCom_Percent { get; set; }
        public int RefCom_Type { get; set; }
        public System.DateTime RefCom_UpdateDate { get; set; }
    }
}
