//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SamanBankTransaction
    {
        public long Sbt_Id { get; set; }
        public string Sbt_DocumentNumber { get; set; }
        public string Sbt_Detail { get; set; }
        public long Sbt_Amount { get; set; }
    }
}
