//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Stg_Id { get; set; }
        public double Stg_MinimunWithdraw { get; set; }
        public double Stg_MaximumPurchase_Level1 { get; set; }
        public double Stg_MaximumPurchase_Level2 { get; set; }
        public double Stg_MaximumPurchase_Level3 { get; set; }
        public int Aff_Id { get; set; }
        public double Stg_MaximumDailyPurchase_Level1 { get; set; }
        public double Stg_MaximumDailyPurchase_Level2 { get; set; }
        public double Stg_MaximumDailyPurchase_Level3 { get; set; }
    
        public virtual Affiliate Affiliate { get; set; }
    }
}
