//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSSender
    {
        public long SMS_Id { get; set; }
        public string SMS_Text { get; set; }
        public string SMS_Reciver { get; set; }
        public System.DateTime SMS_CreateDate { get; set; }
        public int SMS_Status { get; set; }
        public int SMS_Repeat { get; set; }
    }
}
