//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketItem
    {
        public System.Guid TikItm_Id { get; set; }
        public long Tik_Id { get; set; }
        public System.DateTime TikItm_CreateDate { get; set; }
        public string TikItm_Text { get; set; }
        public Nullable<long> AdmUsr_Id { get; set; }
        public Nullable<bool> TikItm_IsLink { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual AdminUser AdminUser { get; set; }
    }
}
