//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.TicketItems = new HashSet<TicketItem>();
        }
    
        public long Tik_Id { get; set; }
        public long Usr_Id { get; set; }
        public System.DateTime Tik_CreateDate { get; set; }
        public long TSub_Id { get; set; }
        public System.DateTime Tik_LatestMsgDate { get; set; }
        public int Tik_Status { get; set; }
        public string Tik_Tag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketItem> TicketItems { get; set; }
        public virtual TicketSubject TicketSubject { get; set; }
        public virtual User User { get; set; }
    }
}
