//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketTemplate
    {
        public long TikTmp_Id { get; set; }
        public string TikTmp_Title { get; set; }
        public string TikTmp_Template { get; set; }
        public bool TikTmp_IsActive { get; set; }
    }
}
