//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.DepositeWallets = new HashSet<DepositeWallet>();
            this.WebhockHistoryTokenViews = new HashSet<WebhockHistoryTokenView>();
            this.DealRequests = new HashSet<DealRequest>();
            this.Tickets = new HashSet<Ticket>();
            this.Transactions = new HashSet<Transaction>();
            this.UserBankCards = new HashSet<UserBankCard>();
            this.UserHistories = new HashSet<UserHistory>();
            this.UserVerificationDocs = new HashSet<UserVerificationDoc>();
            this.UserWithdraws = new HashSet<UserWithdraw>();
            this.WebhockHisories = new HashSet<WebhockHisory>();
            this.LogUserWallets = new HashSet<LogUserWallet>();
            this.Wallets = new HashSet<Wallet>();
        }
    
        public long Usr_Id { get; set; }
        public System.DateTime Usr_CreateDate { get; set; }
        public string Usr_FullName { get; set; }
        public string Usr_Email { get; set; }
        public string Usr_Password { get; set; }
        public string Usr_Phone { get; set; }
        public int Usr_Status { get; set; }
        public Nullable<System.DateTime> Usr_LastLoginDate { get; set; }
        public string Usr_BrowserInfo { get; set; }
        public string Usr_Ip { get; set; }
        public string Usr_IpInfo { get; set; }
        public Nullable<int> Usr_Verification { get; set; }
        public Nullable<double> Usr_BLNC_Balance { get; set; }
        public string Usr_Story { get; set; }
        public Nullable<long> Usr_referrerId { get; set; }
        public Nullable<int> Mch_Id { get; set; }
        public int Usr_VerificationLevel { get; set; }
        public Nullable<int> Aff_Id { get; set; }
        public Nullable<System.Guid> Usr_DirectoryName { get; set; }
        public string Usr_SmsCode { get; set; }
        public string Usr_NationalCode { get; set; }
        public bool Usr_MobileConfirm { get; set; }
        public Nullable<long> Usr_MyRefralCode { get; set; }
        public Nullable<long> Usr_RefralCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepositeWallet> DepositeWallets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebhockHistoryTokenView> WebhockHistoryTokenViews { get; set; }
        public virtual Affiliate Affiliate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealRequest> DealRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBankCard> UserBankCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserHistory> UserHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserVerificationDoc> UserVerificationDocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserWithdraw> UserWithdraws { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebhockHisory> WebhockHisories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogUserWallet> LogUserWallets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wallet> Wallets { get; set; }
    }
}
