//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBankCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserBankCard()
        {
            this.UserWithdraws = new HashSet<UserWithdraw>();
        }
    
        public long UBC_Id { get; set; }
        public string UBC_CardNumber { get; set; }
        public string UBC_Shaba { get; set; }
        public long Usr_Id { get; set; }
        public int UBC_Status { get; set; }
        public Nullable<long> AdmUsr_Id { get; set; }
        public string UBC_AccountNumber { get; set; }
        public int UBC_Bank { get; set; }
        public System.DateTime UBC_CreateDate { get; set; }
        public int Aff_Id { get; set; }
    
        public virtual Affiliate Affiliate { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserWithdraw> UserWithdraws { get; set; }
        public virtual AdminUser AdminUser { get; set; }
    }
}
