//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWalletReservation
    {
        public int UWR_Id { get; set; }
        public System.DateTime UWR_CreateDate { get; set; }
        public int Wal_Id { get; set; }
        public int UWR_CryptoType { get; set; }
        public string UWR_LastTxId { get; set; }
        public int UWR_TransactionCount { get; set; }
    
        public virtual Wallet Wallet { get; set; }
    }
}
