//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWithdraw
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserWithdraw()
        {
            this.BotWithrawTypes = new HashSet<BotWithrawType>();
        }
    
        public long Wit_Id { get; set; }
        public double Wit_Amount { get; set; }
        public bool Wit_AutomatPayment { get; set; }
        public System.DateTime Wit_DateCreate { get; set; }
        public Nullable<bool> Wit_Status { get; set; }
        public Nullable<long> AdmUsr_Id { get; set; }
        public Nullable<long> Doc_Id { get; set; }
        public long Usr_Id { get; set; }
        public int Aff_Id { get; set; }
        public long UBC_Id { get; set; }
        public Nullable<int> Try { get; set; }
        public Nullable<bool> SMS { get; set; }
        public Nullable<bool> Bot { get; set; }
    
        public virtual AdminUser AdminUser { get; set; }
        public virtual Affiliate Affiliate { get; set; }
        public virtual DoucumentUserWithdraw DoucumentUserWithdraw { get; set; }
        public virtual UserBankCard UserBankCard { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BotWithrawType> BotWithrawTypes { get; set; }
    }
}
