//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserHistory
    {
        public long UH_Id { get; set; }
        public System.DateTime UH_CreateDate { get; set; }
        public long Usr_Id { get; set; }
        public string UH_IP { get; set; }
        public string UH_Device { get; set; }
        public string UH_IPInfo { get; set; }
        public string UH_Action { get; set; }
        public string UH_QuerString { get; set; }
        public string UH_BrowserUserAgent { get; set; }
        public string UH_Tag { get; set; }
        public Nullable<int> Mch_Id { get; set; }
    
        public virtual MarketingChannel MarketingChannel { get; set; }
        public virtual User User { get; set; }
    }
}
