//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRelatedAccount
    {
        public long UR_Id { get; set; }
        public System.DateTime UR_CreateDate { get; set; }
        public long UR_CurrentUserId { get; set; }
        public long UR_RelatedUserId { get; set; }
        public string UR_SimilarType { get; set; }
        public string UR_SimilarValue { get; set; }
    }
}
