//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebhockHistoryTokenView
    {
        public long Id { get; set; }
        public string TokenAddress { get; set; }
        public string Address { get; set; }
        public string TokenSymbol { get; set; }
        public string Txid { get; set; }
        public Nullable<long> Time { get; set; }
        public Nullable<int> Confirmations { get; set; }
        public string TokenValue { get; set; }
        public string Value { get; set; }
        public string Coin { get; set; }
        public Nullable<long> Usr_Id { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
