//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WithdrawCrypto
    {
        public long WC_Id { get; set; }
        public string WC_Address { get; set; }
        public double WC_Amount { get; set; }
        public int WC_Status { get; set; }
        public int WC_CryptoType { get; set; }
        public System.Guid Drq_Id { get; set; }
        public System.DateTime WC_CreateDate { get; set; }
        public string WC_Sign { get; set; }
    
        public virtual DealRequest DealRequest { get; set; }
    }
}
